{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nexus3.fullname" . }}
  labels:
    {{- include "nexus3.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}  
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ template "nexus3.fullname" . }}
              servicePort: "nexus-http"
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
      {{- end }}
  {{ end -}}
{{- end }}