apiVersion: v1
kind: Service
metadata:
  name: {{ template "nexus3.name" . }}
  labels:
{{ include "nexus3.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: "nexus-http"
      protocol: TCP
      name: "nexus-http"
  selector:
    app.kubernetes.io/name: {{ include "nexus3.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}