apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "nexus3.fullname" . }}
  labels:
    {{- include "nexus3.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "nexus3.name" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nexus3.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "nexus3.labels" . | nindent 8 }}
    spec:
      {{- if .Values.nexus.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nexus.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: nexus
          image: {{ .Values.nexus.image }}:{{ .Values.nexus.imageTag }}
          imagePullPolicy: {{ .Values.nexus.imagePullPolicy }}
          {{- if .Values.nexus.env }}
          env:
            - name: ORCHESTRATION_ENABLED
              value: "true"
            {{- toYaml .Values.nexus.env | nindent 12 }}
          {{- end }}
          {{- if .Values.nexus.resources }}
          resources:
            {{- toYaml .Values.nexus.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              name: nexus-http
          lifecycle:
            postStart:
              exec:
                command:
                  - /docker-entrypoint.sh
                  - init
          livenessProbe:
            httpGet:
              path: {{ .Values.nexus.livenessProbe.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.nexus.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.nexus.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.nexus.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.nexus.readinessProbe.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.nexus.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.nexus.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.nexus.readinessProbe.failureThreshold }}
          volumeMounts:
            - mountPath: /nexus-data
              name: data
      {{- if .Values.nexus.securityContext }}
      securityContext:
        {{- toYaml .Values.nexus.securityContext | nindent 8 }}
      {{- end }}
      {{- if not .Values.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  volumeClaimTemplates: 
    {{- if .Values.persistence.enabled }}
    - metadata:
        name: data
        labels:
          {{- include "nexus3.labels" . | nindent 10 }}
        {{- if .Values.persistence.annotations }}
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.storageSize | quote }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
    {{- end }}
