sudo: required

services:
  - docker

language: java

env:
  - PATH="$PATH:/tmp/bin"

install: "ci/install.sh"

jdk:
  - openjdk8

jobs:
  include:
    - script: make test
      if: branch != master
    - script: make publish
      if: branch = master