apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    {{ include "nexus3.labels" . | nindent 4 | trim }}
  name: {{ template "nexus3.name" . }}
spec:
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: "{{ regexSplit "/" .Values.nexus.image -1 | last }}:{{ .Values.nexus.imageTag }}"
  postCommit: {}
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{ .Values.build.git.uri | quote }}
      ref: {{ default "master" .Values.build.git.ref | quote }}
    contextDir: {{ .Values.build.contextDir | quote }}
  strategy:
    dockerStrategy:
      {{- if .Values.build.env }}
      env:
        {{- range $ekey, $eval := .Values.build.env }}
        - name: {{ $ekey | quote }}
          value: {{ $eval | quote }}
        {{- end }}
      {{- end }}
      noCache: true
      forcePull: true
    type: Docker
  triggers: []