apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    {{ include "nexus3.labels" . | nindent 4 | trim }}
    build: nexus3
  name: {{ regexSplit "/" .Values.nexus.image -1 | last | quote }}
spec: {}