apiVersion: v1
appVersion: 3.16.1-02
version: 0.0.1-SNAPSHOT
name: nexus3
description: Sonatype Nexus is an open source repository manager
keywords:
  - artifacts
  - dependency
  - management
  - sonatype
  - nexus
  - repository
home: https://www.sonatype.com/nexus-repository-oss
icon: http://www.sonatype.org/nexus/content/uploads/2015/06/Nexus-Logo.jpg
sources:
  - https://github.com/sonatype/nexus-public
  - https://github.com/travelaudience/docker-nexus
  - https://github.com/travelaudience/kubernetes-nexus
  - https://github.com/travelaudience/docker-nexus-backup
maintainers:
  - name: Arnaud Deprez
    email: arnaudeprez@gmail.com