apiVersion: v1
kind: Template
metadata: {}
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    label:
      build: nexus3
    name: nexus3-pipeline
  spec:
    source:
      git:
        uri: https://github.com/arnaud-deprez/nexus3-docker.git
        ref: ${GIT_REF}
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        env:
        - name: SERVICE_NAME
          value: nexus3
        - name: VERSION
          value: "3.13.0"
        - name: VOLUME_CAPACITY
          value: ${VOLUME_CAPACITY}
        - name: DOCKERFILE_PATH
          value: ${DOCKERFILE_PATH}
        jenkinsfilePath: Jenkinsfile
    triggers: []
parameters:
- name: GIT_REF
  value: master
- name: VOLUME_CAPACITY
  displayName: Volume Capacity
  value: 10Gi
- name: DOCKERFILE_PATH
  displayName: Dockerfile path
  value: Dockerfile