apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    label:
      build: nexus3
    name: nexus3-pipeline
  spec:
    source:
      git:
        uri: https://gitlab.com/arnaud-deprez/nexus-scripting.git
        ref: master
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic