apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    label:
      build: nexus3
    name: nexus3-pipeline
  spec:
    source:
      git:
        uri: https://github.com/arnaud-deprez/nexus3-docker.git
        ref: tiller-less
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers: []